apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapi
  labels:
    customer: acg
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  #replicas : 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: jaisai/javaapi:latest
        name: web-ctr
        ports:
        - containerPort: 8080
